const animationsDefault = {
  cx: "Współrzędna X:",
  cy: "Współrzędna Y:",
  x: "Współrzędna X:",
  y: "Współrzędna Y:",
  fill: "Kolor wypełnienia:",
  "fill-opacity": "Krycie wypełnienia:",
  opacity: "Krycie elementu:",
  points: "Współrzędne wierzchołków:",
  stroke: "Kolor obwodu:",
  "stroke-opacity": "Krycie obwodu:",
  height: "Wysokość elementu:",
  "stroke-width": "Szerokość obwodu:",
  width: "Szerokość elementu:",
  transform: "Transformacja:",
  "stroke-dasharray": "Struktura obwodu:",
  r: "Promień:",
  className: "Nazwa stylu css:",
  attributeName: "Animowana wartość:",
  attributeType: "Typ atrybutu:",
  dur: "Czas trwania animacji:",
  from: "Punkt początkowy animacji:",
  to: "Punkt końcowy animacji",
  repeatCount: "Liczba powtórzeń:",
  begin: "Początek animacji:",
  type: "Typ animacji:",
  additive: "Nakładanie się animacji:",
  repeatDur: "Czas powtarzania:",
  calcMode: "Sposób przechodzenia do następnej animacji:",
  keySplines: "Klucze kolejnych położeń:",
  keyTimes: "Czasy kolejnych położeń:",
  values: "Wartości animacji:"
};

export default animationsDefault;
